class Config:
    INITIAL_RANGE = 1000
    MAX_RANGE = 1000
    DROP_PROB_SENDER = 0.0
    DROP_PROB_RECEIVER = 0
    STATE_TIMEOUT = 0.5
    DEAD_RECKONING_ANGLE = 5
    ACCELERATION = 10
    DECELERATION = 10
    MAX_SPEED = 10
    DISPLAY_CELL_SIZE = 0.05
    BUSY_WAITING = False
    DURATION = 30
    SHAPE = 'grid4x4_16_4_spanning_2'
    RESULTS_PATH = 'results'
    MULTICAST = True
    CAMERA = 'w'
    SCALE = 1
    SS_ERROR_MODEL = 1
    SS_ERROR_PERCENTAGE = 0.0
    SS_ACCURACY_PROBABILITY = 0.0
    SS_NUM_SAMPLES = 1
    SS_SAMPLE_DELAY = 0
    STANDBY = False
    GROUP = False
    SWEET_RANGE = (6, 8)
    GROUP_TYPE = 'spanning_2_v2'  # HC: spanning_2, ISR: spanning_2_v2, RSF: spanning_2_v3
    FILE_NAME_KEYS = [('SHAPE', 'S'), ('DEAD_RECKONING_ANGLE', 'D')]
    DIR_KEYS = [('GROUP_TYPE', 'T')]
